{
  config,
  lib,
  pkgs,
  ...
}: let
  cfg = config.boot.loader.boot-selector-switch;
  espMountPoint = config.boot.loader.efi.efiSysMountPoint;

  bootEntryLabel = "Boot Selector Switch";

  configFile =
    pkgs.writeText "boot-selector-switch-config.conf"
    ("# Boot Selector Switch configuration\n"
      + "# Generated by the boot-selector-switch NixOS module — do not edit\n"
      + lib.concatStringsSep "\n"
      (lib.mapAttrsToList (pos: entry: "${pos}=${entry}") cfg.positionMap)
      + "\n");

  # Script to create nixos-latest.conf pointing to the latest NixOS generation.
  # Called from extraInstallCommands in all install modes.
  latestEntryScript = pkgs.writeShellApplication {
    name = "boot-selector-switch-latest-entry";
    runtimeInputs = with pkgs; [coreutils gnused gnugrep findutils];
    text = ''
      ESP="${espMountPoint}"

      # --- Create nixos-latest.conf pointing to the latest NixOS generation ---
      latest=$(find "$ESP/loader/entries" -maxdepth 1 -name 'nixos-generation-*.conf' 2>/dev/null | sort -V | tail -1)
      if [ -n "$latest" ]; then
        cp "$latest" "$ESP/loader/entries/nixos-latest.conf"
        sed -i 's/^title .*/title NixOS (Latest)/' "$ESP/loader/entries/nixos-latest.conf"
        # Add sort-key so it appears before numbered generation entries
        if ! grep -q '^sort-key' "$ESP/loader/entries/nixos-latest.conf"; then
          sed -i '/^title /a sort-key 1-nixos-latest' "$ESP/loader/entries/nixos-latest.conf"
        fi
      fi
    '';
  };

  # Script to register the efi-shim in UEFI boot order.
  # Only called in uefi-first install mode.
  registerBootEntryScript = pkgs.writeShellApplication {
    name = "boot-selector-switch-register";
    runtimeInputs = with pkgs; [coreutils gnugrep efibootmgr util-linux findutils];
    excludeShellChecks = ["SC2162"];
    text = ''
      ESP="${espMountPoint}"

      # Only attempt if EFI variables are accessible and efibootmgr works.
      # During VM image builds, EFI runtime may not be available.
      if ! efibootmgr > /dev/null 2>&1; then
        echo "boot-selector-switch: efibootmgr not functional, skipping boot entry registration"
        exit 0
      fi

      # Find the disk and partition number for our ESP
      ESP_DEV=$(findmnt --noheadings --output SOURCE "$ESP")
      DISK="/dev/$(lsblk -ndo PKNAME "$ESP_DEV")"
      PART=$(cat "/sys/class/block/$(basename "$ESP_DEV")/partition")

      # Remove any existing entries with our label (and only our label)
      efibootmgr | grep "${bootEntryLabel}" | grep -oP 'Boot\K[0-9A-Fa-f]{4}' | while read bootnum; do
        efibootmgr --quiet --bootnum "$bootnum" --delete-bootnum
      done || true

      # Create new boot entry at the front of the boot order, targeting our ESP only
      efibootmgr --quiet --create \
        --disk "$DISK" --part "$PART" \
        --loader '\EFI\boot-selector-switch\boot-selector-switch.efi' \
        --label '${bootEntryLabel}'

      echo "boot-selector-switch: registered in UEFI boot order on $ESP_DEV"
    '';
  };

  # Helper script to toggle the BootSelectorDebug EFI variable from Linux.
  # Uses efivar CLI to read/write the variable.
  debugScript = pkgs.writers.writeNuBin "boot-selector-debug" ''
    const EFIVAR_NAME = "614e5389-b94f-4994-9f26-558928eab8f1-BootSelectorDebug"

    def write_var [value: int] {
      let tmpfile = mktemp -t boot-selector-debug.XXXXXX
      $value | into binary --compact | save --force --raw $tmpfile
      ${pkgs.efivar}/bin/efivar --name $EFIVAR_NAME --write --attributes=non-volatile,boot-service-access,runtime-access --datafile $tmpfile
      rm $tmpfile
    }

    def read_var []: nothing -> bool {
      try {
        let val = ${pkgs.efivar}/bin/efivar --name $EFIVAR_NAME --print-decimal | str trim
        $val != "0"
      } catch {
        false
      }
    }

    def "main on" [] {
      write_var 1
      print "Debug mode enabled. Will take effect on next boot."
    }

    def "main off" [] {
      write_var 0
      print "Debug mode disabled. Will take effect on next boot."
    }

    def "main status" [] {
      if (read_var) {
        print "Debug mode: on"
      } else {
        print "Debug mode: off"
      }
    }

    def main [] {
      main status
    }
  '';
in {
  options.boot.loader.boot-selector-switch = {
    enable = lib.mkEnableOption "boot selector switch EFI shim";

    package = lib.mkOption {
      type = lib.types.package;
      description = "The efi-shim package to install on the ESP.";
    };

    positionMap = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      example = {
        "1" = "nixos-latest.conf";
        "2" = "windows.conf";
        "3" = "netbootxyz.conf";
      };
      description = ''
        Mapping from switch position (1-6) to systemd-boot entry filename.
        Written to config.conf on the ESP, read by the efi-shim at boot.
      '';
    };

    installMode = lib.mkOption {
      type = lib.types.enum ["uefi-first" "systemd-boot-entry"];
      default = "uefi-first";
      description = ''
        How to install the efi-shim in the boot chain.

        - "uefi-first": Register as the first UEFI boot entry via efibootmgr.
          The shim runs before systemd-boot. This is the production mode.

        - "systemd-boot-entry": Add as a systemd-boot menu entry instead.
          Flow: systemd-boot → shim → sets LoaderEntryOneShot → chainloads
          systemd-boot again → boots selected OS. Safe for debugging since a
          hang just requires a power cycle to get back to systemd-boot's menu.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    assertions = [
      {
        assertion = config.boot.loader.systemd-boot.enable;
        message = "boot-selector-switch requires systemd-boot (boot.loader.systemd-boot.enable = true)";
      }
    ];

    boot.loader.efi.canTouchEfiVariables = true;

    # Install the efi-shim and its config to the ESP.
    boot.loader.systemd-boot.extraFiles = {
      "EFI/boot-selector-switch/boot-selector-switch.efi" = "${cfg.package}/boot-selector-switch-efi-shim.efi";
      "EFI/boot-selector-switch/config.conf" = configFile;
    };

    # Always create nixos-latest.conf; only register UEFI boot entry in uefi-first mode.
    boot.loader.systemd-boot.extraInstallCommands = ''
      ${latestEntryScript}/bin/boot-selector-switch-latest-entry
    '' + lib.optionalString (cfg.installMode == "uefi-first") ''
      ${registerBootEntryScript}/bin/boot-selector-switch-register
    '';

    boot.loader.systemd-boot.extraEntries = lib.mkIf (cfg.installMode == "systemd-boot-entry") {
      "boot-selector-switch.conf" = ''
        title Boot Selector Switch
        sort-key 0-boot-selector-switch
        efi /EFI/boot-selector-switch/boot-selector-switch.efi
      '';
    };

    # Add the debug toggle helper to the system
    environment.systemPackages = [debugScript];
  };
}
